### add author
POST http://localhost:8080/authors
Content-Type: application/json

{
  "firstName": "Isaac",
  "lastName": "Asimov"
}

### add author
POST http://localhost:8080/authors
Content-Type: application/json

{
"firstName": "John",
"lastName": "Doe"
}

### add author
POST http://localhost:8080/authors
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

### search author by name
GET http://localhost:8080/authors?searchTerm=Asimov

### add book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Foundation",
  "authorIdentifier": "XXX"
}

### add book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Prelude to Foundation",
  "authorIdentifier": "XXX"
}