### add author
POST http://localhost:8080/authors
Content-Type: application/json

{
"firstName": "John",
"lastName": "Doe"
}

### search author by name
GET http://localhost:8080/authors?searchTerm=Asimov

### add book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Forward the Foundation",
  "publicationDate": "1993",
  "authorIdentifier": "200d7499-8ffa-4bdd-8443-08a36b678886"
}

### search books by author
GET http://localhost:8080/authors/200d7499-8ffa-4bdd-8443-08a36b678886/books

### search books by identifier
GET http://localhost:8080/books/afc1ca0e-803c-483f-85c3-c9657b43936a